Articles.IdentityServerAndAdminUI.Aspire.IdentityServer/Controllers/GrantsController.cs
// Copyright (c) Brock Allen & Dominick Baier. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.


using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Duende.IdentityServer.Services;
using Duende.IdentityServer.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Articles.IdentityServerAndAdminUI.Aspire.IdentityServer.Middleware;
using Articles.IdentityServerAndAdminUI.Aspire.IdentityServer.Models;

namespace Articles.IdentityServerAndAdminUI.Aspire.IdentityServer.Controllers
{
    /// <summary>
    /// This sample controller allows a user to revoke grants given to clients
    /// </summary>
    [SecurityHeaders]
    [Authorize]
    public class GrantsController : Controller
    {
        private readonly IIdentityServerInteractionService interaction;
        private readonly IClientStore clients;
        private readonly IResourceStore resources;

        public GrantsController(IIdentityServerInteractionService interaction,
            IClientStore clients,
            IResourceStore resources)
        {
            this.interaction = interaction;
            this.clients = clients;
            this.resources = resources;
        }

        /// <summary>
        /// Show list of grants
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View("Index", await BuildViewModelAsync());
        }

        /// <summary>
        /// Handle postback to revoke a client
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Revoke(string clientId)
        {
            await interaction.RevokeUserConsentAsync(clientId);
            return RedirectToAction("Index");
        }

        private async Task<GrantsViewModel> BuildViewModelAsync()
        {
            var grants = await interaction.GetAllUserGrantsAsync();

            var list = new List<GrantViewModel>();
            foreach(var grant in grants)
            {
                var client = await clients.FindClientByIdAsync(grant.ClientId);
                if (client != null)
                {
                    var resources = await this.resources.FindResourcesByScopeAsync(grant.Scopes);

                    var item = new GrantViewModel
                    {
                        ClientId = client.ClientId,
                        ClientName = client.ClientName ?? client.ClientId,
                        ClientLogoUrl = client.LogoUri,
                        ClientUrl = client.ClientUri,
                        Description = grant.Description,
                        Created = grant.CreationTime,
                        Expires = grant.Expiration,
                        IdentityGrantNames = resources.IdentityResources.Select(x => x.DisplayName ?? x.Name).ToArray(),
                        ApiGrantNames = resources.ApiScopes.Select(x => x.DisplayName ?? x.Name).ToArray()
                    };

                    list.Add(item);
                }
            }

            return new GrantsViewModel
            {
                Grants = list
            };
        }
    }
}

Articles.IdentityServerAndAdminUI.Aspire.IdentityServer/Views/Shared/_Layout.cshtml
@using Duende.IdentityServer.Extensions
@{
	string name = null;
	if (!true.Equals(ViewData["signed-out"]))
	{
		name = Context.User?.GetDisplayName();
	}
	bool signedIn = !string.IsNullOrWhiteSpace(name);
}
<!DOCTYPE html>
<html class="no-js bg-navy-darker" lang="en-gb">
<head>
	<meta charset="utf-8" />
	<title>IdentityServer</title>
	<meta name="robots" content="noindex" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width,shrink-to-fit=no,initial-scale=1,minimum-scale=1" />
	<link href="~/fonts/fontawesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
	<link href="~/css/site.min.css" rel="stylesheet" media="screen" asp-append-version="true" />
	<link href="~/css/print.min.css" rel="stylesheet" media="print" asp-append-version="true" />
	<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" asp-append-version="true" />
	<meta name="theme-color" content="#000913" />
	<meta name="format-detection" content="telephone=no" />
</head>
<body id="top" class="preload bg-navy-darker text-white text-center text-base font-sans leading-normal">

	<a class="skip-link sr-only sr-only-focusable bg-white font-semibold text-copy px-4 py-2 no-print" href="#main">Skip to content</a>

	<div class="bg-black-darker px-6 py-3 no-print">
		<nav class="flex items-center justify-end container text-xs leading-none text-grey-lighter text-right mx-auto" aria-label="Account">
			<span class="hidden sm:block fas fa-user-alt opacity-75 mr-2" aria-hidden="true"></span>
			<ul class="flex items-center list-reset">
				@if (signedIn)
				{
					<li class="flex items-center mr-2 sm:mr-3" aria-hidden="true">
						<span class="block text-right w-48 sm:w-auto sm:max-w-xs truncate">@name</span>
						<span class="block bg-grey w-1 h-1 ml-2 rounded-full sm:ml-3"></span>
					</li>
				}
				<li>
					@if (signedIn)
					{
						<a class="text-grey-lighter hover:text-white trans" asp-action="Logout" asp-controller="Account">Logout</a>
					}
					else
					{
						<a class="text-grey-lighter hover:text-white trans" asp-action="Login" asp-controller="Account">Login</a>
					}
				</li>
			</ul>
		</nav>
	</div>

	<header id="header" class="bg-navy border-b border-white-25 text-white px-6" role="banner">
		<div class="flex items-center justify-between container mx-auto h-header">
			<a class="font-semibold flex items-center bg-red text-white px-5 py-1 rounded-full hover:bg-red-dark focus:shadow-outline focus:outline-none trans-bg" href="https://www.identityserver.com" target="_blank">
				<span>IdentityServer</span>
				<span class="text-white-75 font-normal no-print">.com</span>
			</a>
			<nav id="nav" class="no-print">
				<ul class="flex flex-wrap items-center list-reset">
					<li class="sm:mr-5">
						<a class="block p-1 text-navy-lighter hover:text-white trans-color" asp-action="Index" asp-controller="Home">
							Home
						</a>
					</li>
					<li class="hidden sm:block sm:mr-5">
						<a class="block p-1 text-navy-lighter hover:text-white trans-color" asp-action="Index" asp-controller="Grants">
							Grants
						</a>
					</li>
					<li class="hidden sm:block">
						<a class="flex items-center bg-navy-light font-semibold text-white px-5 py-1 hover:bg-navy-lightest hover:text-navy rounded-full trans" href="https://www.identityserver.com/products" target="_blank">
							<span class="capitalize md:normal-case">
								<span class="hidden md:inline">Our</span> products
							</span>
							<span class="fas fa-long-arrow-alt-right ml-2" aria-hidden="true"></span>
						</a>
					</li>
				</ul>
			</nav>
		</div>
	</header>

	<main id="main" class="bg-navy-lightest text-copy focus:outline-none" role="main" tabindex="-1">

		@RenderSection("banner", false)

		<div id="content">

			<div class="row-block">
				<div class="container text-left mx-auto">
					<div class="flex flex-wrap -mt-6 -ml-6 lg:-mt-12 lg:-ml-12 xl:-mt-16 xl:-ml-16">

						<div id="body" class="text-left mx-auto pt-6 pl-6 w-full md:w-1/2 lg:w-2/3 lg:pt-12 lg:pl-12 xl:pt-16 xl:pl-16">
							@RenderBody()
						</div>

						<aside class="text-left mx-auto pt-6 pl-6 w-full md:w-1/2 lg:w-1/3 lg:pt-12 lg:pl-12 xl:pt-16 xl:pl-16 print-grid">

							<section class="bg-red-lightest border-b-3 border-red overflow-hidden rounded shadow-md print-grid__col-1/2">
								<h2 class="bg-red text-base text-white p-4">
									<span class="fas fa-wrench fa-fw mr-1" aria-hidden="true"></span>
									Your own customised <abbr title="Single sign-on">SSO</abbr> solution
								</h2>
								<div class="p-4 pb-6">
									<p class="text-sm">We can develop a customised IdentityServer solution to fit your needs:</p>
									<ul class="list-reset text-sm mt-3">
										<li class="flex items-start">
											<span class="fas fa-check-circle flex-no-shrink text-red leading-normal mr-2" aria-hidden="true"></span>
											<span>Built to your exact requirements</span>
										</li>
										<li class="flex items-start mt-1">
											<span class="fas fa-check-circle flex-no-shrink text-red leading-normal mr-2" aria-hidden="true"></span>
											<span>Seamless integration with your IT infrastructure</span>
										</li>
										<li class="flex items-start mt-1">
											<span class="fas fa-check-circle flex-no-shrink text-red leading-normal mr-2" aria-hidden="true"></span>
											<span>Full source code</span>
										</li>
									</ul>
									<p class="mt-6 text-center">
										<span class="hidden" aria-hidden="true">Email: sales@identityserver.com</span>
										<a class="btn btn-small no-print" href="mailto:sales@identityserver.com?subject=Custom+SSO+solutions" target="_blank">Enquire Now</a>
									</p>
								</div>
							</section>

							<section class="bg-navy-lightest border-b-3 border-navy overflow-hidden rounded shadow-md mt-6 lg:mt-8 print-grid__col-1/2">
								<h2 class="bg-navy text-base text-white p-4">
									<span class="far fa-question-circle fa-fw mr-1" aria-hidden="true"></span>
									Looking for IdentityServer support?
								</h2>
								<div class="p-4 pb-6">
									<p class="text-sm">We can help with your IdentityServer solution providing expert guidance, support and consultancy:</p>
									<ul class="list-reset text-sm mt-3">
										<li class="flex items-start">
											<span class="fas fa-check-circle flex-no-shrink text-navy leading-normal mr-2" aria-hidden="true"></span>
											<span>Remote development support</span>
										</li>
										<li class="flex items-start mt-1">
											<span class="fas fa-check-circle flex-no-shrink text-navy leading-normal mr-2" aria-hidden="true"></span>
											<span>IdentityServer production support</span>
										</li>
										<li class="flex items-start mt-1">
											<span class="fas fa-check-circle flex-no-shrink text-navy leading-normal mr-2" aria-hidden="true"></span>
											<span>Formal health checks</span>
										</li>
									</ul>
									<p class="mt-6 text-center">
										<span class="hidden" aria-hidden="true">Email: sales@identityserver.com</span>
										<a class="btn btn-small btn-secondary no-print" href="mailto:sales@identityserver.com?subject=IdentityServer+support" target="_blank">Enquire Now</a>
									</p>
								</div>
							</section>

						</aside>

					</div>
				</div>
			</div>

			<aside id="site-info" class="row-block">
				<div class="max-w-md text-navy-light text-sm text-center mx-auto">
					<p>This implementation of IdentityServer is completely open source. Please go ahead and change the branding to meet your requirements; however you will need a license from <a class="text-red-dark font-bold hover:text-navy trans" href="https://duendesoftware.com/" target="_blank">Duende Software</a> to deploy it. If you need any support or are interested in our commercial options for IdentityServer, please feel free to contact us at <a class="text-red-dark font-bold hover:text-navy trans" href="mailto:sales@identityserver.com?subject=Commercial" target="_blank">sales@identityserver.com</a></p>
				</div>
			</aside>

		</div>
	</main>

	<div class="relative z-30 no-print">
		<p class="absolute pin-b pin-l pin-r -mb-5 -ml-4 z-20">
			<a class="bg-navy-darker text-navy-lighter h-10 w-10 rounded-full flex items-center justify-center mx-auto hover:bg-red hover:text-white trans" href="#top">
				<span class="fas fa-arrow-up" aria-hidden="true"></span>
				<span class="sr-only">Back To Top</span>
			</a>
		</p>
	</div>

	<footer id="footer" class="bg-navy-darker text-navy-lighter px-6 py-10 text-xs relative z-20" role="contentinfo">
		<div class="flex flex-wrap sm:flex-no-wrap items-center sm:justify-between container text-left mx-auto">
			<p class="mb-4 sm:mb-0 w-full sm:w-auto">&copy; @DateTime.Now.Year <a class="hover:text-white trans" href="https://www.rocksolidknowledge.com" target="_blank">Rock Solid Knowledge</a></p>
			<p class="list-reset w-full sm:w-auto no-print">
				<a class="hover:text-white trans" href="https://www.identityserver.com/" target="_blank">
					IdentityServer.com
				</a>
			</p>
		</div>
	</footer>

	<script src="~/js/site.min.js" asp-append-version="true"></script>
	@RenderSection("scripts", false)

</body>
</html>

Articles.IdentityServerAndAdminUI.Aspire.IdentityServer/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
	<div class="message message-error" role="alert">
		<div>
			<h2 class="text-base">Error</h2>
			<div asp-validation-summary="All"></div>
		</div>
	</div>
}